# Generated by Django 3.0.5 on 2020-04-28 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
        ('campers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Camp'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='camperPic/'),
        ),
    ]
