# Generated by Django 3.0.5 on 2020-04-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campers', '0002_auto_20200428_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camper',
            name='profile_pic',
        ),
    ]
