# Generated by Django 3.0.5 on 2020-04-25 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_staff_department'),
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.Staff'),
        ),
    ]
