# Generated by Django 3.0.5 on 2020-04-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='postscript',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
