# Generated by Django 3.0.5 on 2020-04-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=255)),
                ('blood_type', models.CharField(max_length=2)),
                ('birthday', models.DateField()),
                ('religion', models.CharField(max_length=255)),
                ('food_allergy', models.CharField(max_length=255)),
                ('congenital_disease', models.CharField(max_length=255)),
                ('shirt_size', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('parent_phone', models.CharField(max_length=10)),
                ('parent_name', models.CharField(max_length=255)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal')),
            ],
        ),
    ]
