# Generated by Django 3.0.5 on 2020-04-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=8, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('nick_name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255)),
                ('blood_type', models.CharField(max_length=2)),
                ('birthday', models.DateField()),
                ('religion', models.CharField(max_length=255)),
                ('food_allergy', models.CharField(max_length=255)),
                ('congenital_disease', models.CharField(max_length=255)),
                ('shirt_size', models.CharField(max_length=1)),
                ('profile_pic', models.ImageField(upload_to='profiles/')),
            ],
        ),
    ]
