# Generated by Django 3.0.5 on 2020-04-18 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=255)),
                ('blood_type', models.CharField(max_length=2)),
                ('birthday', models.DateField()),
                ('religion', models.CharField(max_length=255)),
                ('food_allergy', models.CharField(max_length=255)),
                ('congenital_disease', models.CharField(max_length=255)),
                ('shirt_size', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
