# Generated by Django 3.0.5 on 2020-04-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='blood_type',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='congenital_disease',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='food_allergy',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='personal',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='profile_pic',
            field=models.ImageField(default='profiles/profile.png', upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='religion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
