# Generated by Django 3.0.5 on 2020-04-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='congenital_disease',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='food_allergy',
            field=models.TextField(default='-'),
        ),
    ]
