# Generated by Django 3.0.5 on 2020-04-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20200427_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
