# Generated by Django 3.0.5 on 2020-04-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20200427_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='profile_pic',
            field=models.ImageField(upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='shirt_size',
            field=models.CharField(max_length=5),
        ),
    ]
