# Generated by Django 3.0.5 on 2020-04-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('activity', models.CharField(max_length=255)),
                ('sub_time', models.TimeField()),
                ('desc', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255, null=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Camp')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camp.Department')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('mc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camp.MC')),
            ],
        ),
    ]
