# Generated by Django 3.0.5 on 2020-04-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camp', '0002_mc_staff'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('activity', models.CharField(max_length=255)),
                ('sub_time', models.DateTimeField()),
                ('desc', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.Department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('mc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.MC')),
            ],
        ),
    ]
