# Generated by Django 3.0.5 on 2020-04-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='camp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camp.Camp'),
        ),
    ]
