# Generated by Django 3.0.5 on 2020-04-27 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_mc_staff'),
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camp.Department'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='mc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camp.MC'),
        ),
    ]
