# Generated by Django 3.0.5 on 2020-04-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_auto_20200427_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='sub_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flow',
            name='time_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flow',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
